server:
  port: 8080
  servlet:
    context-path: /${spring.application.name}

info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"
    
spring:
  application:
    name: optimizingrequests
    
logging:
  level:
    root: INFO