server:
  port: 8080
  servlet:
    context-path: /${spring.application.name}

info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"
    
spring:
  application:
    name: optimizingrequests
    
logging:
  level:
    root: INFO
    
feign:
  httpclient:
    disableSslValidation: true
    enabled: false
  okhttp:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 7000
        readTimeout: 7000
    
external:
    deck: 
      url: https://<url>
    